### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Nneji123** [SKbarbon/Flet_StoryBoard#3]
I like this tool and I'd like to contribute to it. How do I get started?

**Comment by SKbarbon** [comment]
Thank you for your interest in contributing to our Python Flet StoryBoard library on GitHub! We appreciate your willingness to help improve our project.

To get started, we recommend that you familiarize yourself with the codebase and functionality of the library. Although we don't currently have a tutorial documentation available, you can find an overview of the library's features and usage in the main README.md file. 
*Thats why i recomend you to wait until we have a good documentations about the library.

Once you have a good understanding of the library, you can fork the repository and make the changes or additions that you would like to contribute. We encourage you to follow best practices for coding and documentation and to make sure that your changes align with the goals and scope of the project.

When you are ready to submit your changes, please create a pull request so that we can review your code and provide feedback. We appreciate your effort in contributing to our project and look forward to reviewing your contributions. If you have any questions or need further guidance, please don't hesitate to ask.

**Comment by SKbarbon** [comment]
Now there is a new document to learn from. You can check it here:
[Docs](https://github.com/SKbarbon/Flet_StoryBoard/wiki)
